### ISSUE TITLE
Can't install on box: node:6.2.1

### ISSUE THREAD

**Issue by tupy** [wantedly/step-pretty-slack-notify#34]
### Intall-packages

```
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libruby2.1 ruby2.1 rubygems-integration
Suggested packages:
  ri ruby-dev bundler
The following NEW packages will be installed:
  libruby2.1 ruby ruby2.1 rubygems-integration
0 upgraded, 4 newly installed, 0 to remove and 79 not upgraded.
Need to get 3581 kB of archives.
After this operation, 15.3 MB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main rubygems-integration all 1.8 [4514 B]
Get:2 http://httpredir.debian.org/debian/ jessie/main ruby2.1 amd64 2.1.5-2+deb8u3 [276 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main ruby all 1:2.1.5+deb8u2 [9688 B]
Get:4 http://httpredir.debian.org/debian/ jessie/main libruby2.1 amd64 2.1.5-2+deb8u3 [3290 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 3581 kB in 11s (323 kB/s)
Selecting previously unselected package rubygems-integration.
(Reading database ... 21152 files and directories currently installed.)
Preparing to unpack .../rubygems-integration_1.8_all.deb ...
Unpacking rubygems-integration (1.8) ...
Selecting previously unselected package libruby2.1:amd64.
Preparing to unpack .../libruby2.1_2.1.5-2+deb8u3_amd64.deb ...
Unpacking libruby2.1:amd64 (2.1.5-2+deb8u3) ...
Selecting previously unselected package ruby2.1.
Preparing to unpack .../ruby2.1_2.1.5-2+deb8u3_amd64.deb ...
Unpacking ruby2.1 (2.1.5-2+deb8u3) ...
Selecting previously unselected package ruby.
Preparing to unpack .../ruby_1%3a2.1.5+deb8u2_all.deb ...
Unpacking ruby (1:2.1.5+deb8u2) ...
Setting up rubygems-integration (1.8) ...
Setting up libruby2.1:amd64 (2.1.5-2+deb8u3) ...
Setting up ruby2.1 (2.1.5-2+deb8u3) ...
Setting up ruby (1:2.1.5+deb8u2) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
```
### pretty-slack-notify

```
Ruby Version: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
Ruby Path: /usr/bin/ruby
Install User: root

Installing slack-notifier...
ERROR:  Loading command: install (LoadError)
    /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- slack-notifier (LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /pipeline/pretty-slack-notify-58676b77-f83d-4df6-8c9a-a2a356eceb6f/run.rb:3:in `<main>'
```

**Comment by rafaelverger** [comment]
`libssl-dev` is also a necessary package;

```
- install-packages:
        packages: libssl-dev ruby
```

**Comment by awakia** [comment]
@rafaelverger thank you for your help
