### ISSUE TITLE
Pretty-slack-notify fails since around November 1st, 2017

### ISSUE THREAD

**Issue by Kotoriii** [wantedly/step-pretty-slack-notify#47]
All my projects fail to notify on build success / failure in the `pretty-slack-notify` after-step.
This is where it fails:
```
Bundle complete! 112 Gemfile dependencies, 282 gems now installed.
Bundled gems are installed into `/pipeline/cache/bundle-install`
bundler: failed to load command: /pipeline/pretty-slack-notify-9d35dd43-0865-424e-baed-919999a73905/run.rb (/pipeline/pretty-slack-notify-9d35dd43-0865-424e-baed-919999a73905/run.rb)
LoadError: cannot load such file -- slack-notifier
  /pipeline/pretty-slack-notify-9d35dd43-0865-424e-baed-919999a73905/run.rb:3:in `require'
  /pipeline/pretty-slack-notify-9d35dd43-0865-424e-baed-919999a73905/run.rb:3:in `<top (required)>'
```

**Comment by shibukk** [comment]
@Kotoriii I tried this and I could fix.

```diff
build:
    after-steps:
        - install-packages:
            packages: ruby
-       - wantedly/pretty-slack-notify:
+       - pasonatquila/pretty-slack-notify:
            webhook_url: $SLACK_WEBHOOK_URL
```

FYI:
https://github.com/pasonatquila/step-pretty-slack-notify/commit/f247cb36c2092dc6dcdc4359f8c879cb227f1c29
